=== dalelane/kafka-demos/schemas/BLUESKY.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "BlueskyUpdate",
    "type": "object",
    "properties": {
      "id": {
        "type": "object",
        "description": "ID of the status update",
        "properties": {
          "uri": {
            "type": "string"
          },
          "cid": {
            "type": "string"
          }
        },
        "required": [
          "uri",
          "cid"
        ]
      },
      "text": {
        "type": "string",
        "description": "Plain text copy of the status update posted"
      },
      "langs": {
        "type": "array",
        "description": "Language of this status update. ISO 639 Part 1 two-letter language code. Array can be empty if the language is unknown",
        "items": [
          {
            "type": "string"
          }
        ]
      },
      "createdAt": {
        "type": "integer",
        "description": "Kafka Connect timestamp field - expressed as milliseconds since epoch"
      },
      "author": {
        "type": "object",
        "description": "details of the user who posted the update",
        "properties": {
          "handle": {
            "type": "string",
            "description": "unique user handle - e.g. theirusername.bsky.social"
          },
          "displayName": {
            "type": "string",
            "description": "friendly displayable username"
          },
          "avatar": {
            "type": "string",
            "description": "URL to the profile picture used by the user"
          }
        },
        "required": [
          "handle"
        ]
      }
    },
    "required": [
      "id",
      "text",
      "langs",
      "createdAt",
      "author"
    ]
}

=== dalelane/kafka-demos/sample-messages/BLUESKY.json
{
    "id": {
      "uri": "at://did:plc:gssjrx12z2xtqa7gl2rny3nm/app.bsky.feed.post/3lbcqs9nsnc2a",
      "cid": "bafybahfjnjjypu6ewy5iryvnm2nu3jwiajscbifi2dtgab7ogutkoi2caa"
    },
    "text": "User post in plain text here",
    "langs": [
      "en"
    ],
    "createdAt": 1732030120973,
    "author": {
      "handle": "username.bsky.social",
      "displayName": "User Name",
      "avatar": "https://cdn.bsky.app/img/avatar/plain/did:plc:gssjrx67z2hfkds7gl3rny3nm/bafkreiebwqcuhgfdjksuhy5wbwfn3by35oa77hwkagm3fliksrnuow2phoz1@jpeg"
    }
}
