=== dalelane/kafka-demos/schemas/IBMMQ.SOURCE.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "MQOrder",
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "format": "uuid"
      },
      "customer": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "name": {
            "type": "object",
            "properties": {
              "firstname": {
                "type": "string"
              },
              "lastname": {
                "type": "string"
              }
            },
            "required": [
              "lastname"
            ]
          },
          "phone": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "number": {
                "type": "string"
              }
            },
            "required": [
              "type",
              "number"
            ]
          }
        },
        "required": [
          "id",
          "name",
          "phone"
        ]
      },
      "creditcard": {
        "type": "object",
        "properties": {
          "number": {
            "type": "string"
          },
          "expiry": {
            "type": "string"
          }
        },
        "required": [
          "number",
          "expiry"
        ]
      },
      "products": {
        "type": "array",
        "items": [
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "format": "uuid"
              },
              "description": {
                "type": "string"
              },
              "cost": {
                "type": "number"
              },
              "quantity": {
                "type": "integer"
              }
            },
            "required": [
              "id",
              "description",
              "cost",
              "quantity"
            ]
          }
        ]
      },
      "ordertime": {
        "type": "string",
        "pattern": "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d{1,3}$"
      }
    },
    "required": [
      "id",
      "customer",
      "products",
      "ordertime"
    ]
}

=== dalelane/kafka-demos/sample-messages/IBMMQ.SOURCE.json
{
    "id": "f7ef4939-645e-4a16-8bef-494235e6b28e",
    "customer": {
        "id": "3daf1bc0-9514-4226-8364-1852c403e39f",
        "name": {
            "firstname": "Melissa",
            "lastname": "Goodwin"
        },
        "phone": {
            "type": "landline",
            "number": "056 1565 9006"
        }
    },
    "creditcard": {
        "number": "6771-8970-5432-3442",
        "expiry": "10/27"
    },
    "products": [
        {
            "id": "d9132411-0e26-4692-9002-d20dd91d68b0",
            "description": "Synergistic Iron Gloves",
            "cost": 64.45,
            "quantity": 1
        }
    ],
    "ordertime": "2024-10-26 22:05:38.340"
}
