=== dalelane/kafka-demos/schemas/XBOX.ACHIEVEMENTS.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "XboxAchievements",
    "type": "object",
    "properties": {
      "date": {
        "type": "string"
      },
      "gamertag": {
        "type": "string"
      },
      "gamername": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "icon": {
        "type": "string"
      },
      "contentname": {
        "type": "string"
      },
      "contentimage": {
        "type": "string"
      },
      "platform": {
        "type": "string"
      },
      "gamerscore": {
        "type": "integer"
      },
      "rarityscore": {
        "type": "integer"
      },
      "raritycategory": {
        "type": "string"
      }
    },
    "required": [
      "date",
      "gamertag",
      "gamername",
      "name",
      "description",
      "icon",
      "contentname",
      "contentimage",
      "platform",
      "gamerscore",
      "rarityscore",
      "raritycategory"
    ]
}

=== dalelane/kafka-demos/sample-messages/XBOX.ACHIEVEMENTS.json
{
    "date": "2024-10-13T09:18:37.191Z",
    "gamertag": "alanchatt123",
    "gamername": "Alan Chatt",
    "name": "Power Shot",
    "description": "Score a goal using the power shot mechanic",
    "icon": "http://images-eds.xboxlive.com/image?url=27S1DHqE.cHkmFg4nspsdwPTnSdXfPpBspCOeUi8nKgMFKeuOeoopokmcqpfijIk8ewqrb6KzKRUQ8aZ75QghPGNkpZlqr5xu0YNJmxunxBnm34IoeUxSNF9fcf3Izlr",
    "contentname": "EA SPORTS FCâ„¢ 25 Xbox Series X|S",
    "contentimage": "http://store-images.s-microsoft.com/image/apps.19344.13738418562228928.2f1b7c14-3e99-4a31-8375-ffc682a65cb0.2b4e09e5-281d-4184-9cf6-70277a5a54b5",
    "platform": "XboxOne",
    "gamerscore": 15,
    "rarityscore": 47,
    "raritycategory": "Common"
}
